### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by hhkaos** [hhkaos/awesome-arcgis#20]
Taken from here

# TODO List

**Table of contents**

- [Pending](#pending)
- [In progress](#in-progress)
- [Done](#done)
- [TODO List (Esri Spain):](#todo-list-esri-spain)
  - [Pending](#pending-1)
  - [In progress](#in-progress-1)
  - [Done](#done-1)

## Pending
* [ ] The ArcGIS Book: https://learn.arcgis.com/en/arcgis-book/
* [ ] Add ideas.esri.com somewhere
* [ ] Add codesharing.arcgis.com
* [ ] Add http://odoe.net/blog/ articles
* [ ] Add MOOCs
* [ ] Add free tools from marketplace (like admintools)
* [ ] Add indoor somewhere
* [ ] Add [Intl Github accounts](https://github.com/search?utf8=%E2%9C%93&q=esri&type=Users&ref=searchresults)
* [ ] Add https://github.com/mraad
* [ ] Add how to make your own geocoder & network

## In progress
* [ ] Add lessons from [learn.arcgis.com](http://learn.arcgis.com/en/)
* [ ] Add developer-support folders to each technology
* [ ] Add every https://github.com/Esri/ repo to a developer profile
* [ ] Add awesome lists for each technology on it folder (angular, dojo, etc)

### Pending
* [ ] Add videos Confe '16: [SESIONES TEMÁTICAS](https://www.youtube.com/playlist?list=PLoptan2utx15GTm4xlTbdGg7fFdZHeZwT)
* [ ] Add videos Confe '16: [MESAS DE EXPERTOS](https://www.youtube.com/playlist?list=PLoptan2utx17ZUfvws6DNRH6D1f7kCfiK)
* [ ] Add videos Confe '16: [SESIONES TÉCNICAS](https://www.youtube.com/playlist?list=PLoptan2utx16niLrOMprCThrbrnmnTjGI)
* [ ] Add videos Confe '16: [PLENARIA](https://www.youtube.com/playlist?list=PLoptan2utx17PiimHANwZ8VNOEAGHiXfF)
* [ ] Add "introducción a arcgis online para desarrolladores" y resto de charlas de desarrolladores.esri.es y geodevelopers
y repos de esri españa
